{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/volt\/applesignin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/applesignin"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerPresentationContextProviding","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","doc:\/\/com.KCDev.Volt\/objc(pl)NSObject","doc:\/\/com.KCDev.Volt\/s7CVarArgP","doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP","doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","doc:\/\/com.KCDev.Volt\/SQ","doc:\/\/com.KCDev.Volt\/SH","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/ThirdPartyAuth"],"type":"conformsTo","kind":"relationships"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@Volt@objc(cs)AppleSignIn","title":"AppleSignIn","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleSignIn"}],"modules":[{"name":"Volt"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleSignIn"}]}],"kind":"declarations"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/init(callback:)"]},{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/callback"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/performRequests()"],"title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerPresentationContextProviding-Implementations"],"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn"},"sections":[],"references":{"doc://com.KCDev.Volt/objc(pl)ASAuthorizationControllerPresentationContextProviding":{"identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerPresentationContextProviding","type":"unresolvable","title":"ASAuthorizationControllerPresentationContextProviding"},"doc://com.KCDev.Volt/SQ":{"identifier":"doc:\/\/com.KCDev.Volt\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.KCDev.Volt/objc(pl)DSM_Ignore":{"identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","type":"unresolvable","title":"DocuSignSDK.DSM_Ignore"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn":{"url":"\/documentation\/volt\/applesignin","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleSignIn","kind":"identifier"}],"abstract":[],"title":"AppleSignIn","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","kind":"symbol"},"doc://com.KCDev.Volt/SH":{"identifier":"doc:\/\/com.KCDev.Volt\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.KCDev.Volt/objc(pl)DSM_Optional":{"type":"unresolvable","title":"DocuSignSDK.DSM_Optional","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/performRequests()":{"role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/performRequests()","abstract":[],"type":"topic","title":"performRequests()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performRequests"},{"kind":"text","text":"()"}],"url":"\/documentation\/volt\/applesignin\/performrequests()","kind":"symbol"},"doc://com.KCDev.Volt/objc(pl)ASAuthorizationControllerDelegate":{"identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerDelegate","title":"ASAuthorizationControllerDelegate","type":"unresolvable"},"doc://com.KCDev.Volt/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.KCDev.Volt/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.KCDev.Volt\/s7CVarArgP"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/init(callback:)":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/init(callback:)","type":"topic","url":"\/documentation\/volt\/applesignin\/init(callback:)","title":"init(callback:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4Volt22ThirdPartyAuthCallbacka","text":"ThirdPartyAuthCallback","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt/ThirdPartyAuth":{"type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/ThirdPartyAuth","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ThirdPartyAuth","kind":"identifier"}],"title":"ThirdPartyAuth","abstract":[],"url":"\/documentation\/volt\/thirdpartyauth","navigatorTitle":[{"text":"ThirdPartyAuth","kind":"identifier"}],"kind":"symbol"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/ASAuthorizationControllerPresentationContextProviding-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerPresentationContextProviding-Implementations","type":"topic","url":"\/documentation\/volt\/applesignin\/asauthorizationcontrollerpresentationcontextproviding-implementations","title":"ASAuthorizationControllerPresentationContextProviding Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/ASAuthorizationControllerDelegate-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations","type":"topic","url":"\/documentation\/volt\/applesignin\/asauthorizationcontrollerdelegate-implementations","title":"ASAuthorizationControllerDelegate Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.KCDev.Volt/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"},"doc://com.KCDev.Volt/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)NSObject"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/callback":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/callback","type":"topic","url":"\/documentation\/volt\/applesignin\/callback","title":"callback","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:4Volt22ThirdPartyAuthCallbacka","kind":"typeIdentifier","text":"ThirdPartyAuthCallback"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"AppleSignIn"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"AppleSignIn","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AppleSignIn","kind":"identifier"}]},{"value":[{"title":"Default Implementations","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerPresentationContextProviding-Implementations"],"generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerPresentationContextProviding"],"title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppleSignIn"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/title","value":"AppleSignIn"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/fragments","value":[{"kind":"identifier","text":"AppleSignIn"}]}]}]}