{"topicSections":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/cacheInProgress","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/cacheUpdateInProgress","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/cachedTemplate","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/failedToCache","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/uncachedTemplate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheInProgressTemplateWithId:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheUpdateInProgressTemplateWithId:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cachedTemplateWithId:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:failedToCacheTemplateWithId:error:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:uncachedTemplateWithId:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/dsmtemplatehandler"]},{"paths":["\/documentation\/volt\/dsmtemplatehandler"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt"]]},"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"generated":true,"title":"DocuSign Integration","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DocuSignManager","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMHandler","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMAccountInfoWrapper"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"symbolKind":"class","role":"symbol","modules":[{"name":"Volt"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSMTemplateHandler","kind":"identifier"}],"roleHeading":"Class","title":"DSMTemplateHandler","externalID":"c:@M@Volt@objc(cs)DSMTemplateHandler"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)DSMTemplatesManagerDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","doc:\/\/com.KCDev.Volt\/objc(pl)NSObject","doc:\/\/com.KCDev.Volt\/s7CVarArgP","doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP","doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","doc:\/\/com.KCDev.Volt\/SQ","doc:\/\/com.KCDev.Volt\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSMTemplateHandler"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.KCDev.Volt/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/SQ","title":"Swift.Equatable"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/cacheInProgress":{"title":"cacheInProgress","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/cacheinprogress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cacheInProgress"},{"kind":"text","text":": @"},{"kind":"typeIdentifier","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/cacheInProgress","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/uncachedTemplate":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/uncachedtemplate","abstract":[],"kind":"symbol","title":"uncachedTemplate","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/uncachedTemplate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uncachedTemplate"},{"text":": @","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}]},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSMTemplateHandler","kind":"identifier"}],"url":"\/documentation\/volt\/dsmtemplatehandler","abstract":[],"kind":"symbol","title":"DSMTemplateHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","type":"topic"},"doc://com.KCDev.Volt/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.KCDev.Volt/documentation/Volt/DSMAccountInfoWrapper":{"navigatorTitle":[{"text":"DSMAccountInfoWrapper","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSMAccountInfoWrapper"}],"url":"\/documentation\/volt\/dsmaccountinfowrapper","abstract":[],"kind":"symbol","title":"DSMAccountInfoWrapper","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMAccountInfoWrapper","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/cachedTemplate":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/cachedtemplate","abstract":[],"kind":"symbol","title":"cachedTemplate","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/cachedTemplate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cachedTemplate","kind":"identifier"},{"text":": @","kind":"text"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"typeIdentifier"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}]},"doc://com.KCDev.Volt/documentation/Volt/DocuSignManager":{"title":"DocuSignManager","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DocuSignManager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocuSignManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocuSignManager"}],"abstract":[{"type":"codeVoice","code":"DocuSignManager"},{"text":" manages DocuSign-related operations in the Volt app.","type":"text"}],"url":"\/documentation\/volt\/docusignmanager","role":"symbol"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/failedToCache":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/failedtocache","abstract":[],"kind":"symbol","title":"failedToCache","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/failedToCache","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedToCache"},{"text":": @","kind":"text"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"typeIdentifier"},{"text":" (","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}]},"doc://com.KCDev.Volt/objc(pl)DSMTemplatesManagerDelegate":{"identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSMTemplatesManagerDelegate","title":"DSMTemplatesManagerDelegate","type":"unresolvable"},"doc://com.KCDev.Volt/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.KCDev.Volt/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:uncachedTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:uncachedtemplatewithid:)","navigatorTitle":[{"kind":"identifier","text":"templatesManager:uncachedTemplateWithId:"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:uncachedTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:uncachedTemplateWithId:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSMTemplatesManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"text":", ","kind":"text"},{"text":"uncachedTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP"},"doc://com.KCDev.Volt/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"},"doc://com.KCDev.Volt/objc(pl)DSM_Ignore":{"title":"DocuSignSDK.DSM_Ignore","type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/cacheUpdateInProgress":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/cacheupdateinprogress","abstract":[],"kind":"symbol","title":"cacheUpdateInProgress","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/cacheUpdateInProgress","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cacheUpdateInProgress","kind":"identifier"},{"text":": @","kind":"text"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"typeIdentifier"},{"text":" (","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}]},"doc://com.KCDev.Volt/objc(pl)DSM_Optional":{"identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","title":"DocuSignSDK.DSM_Optional","type":"unresolvable"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/init":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"init","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/init","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:failedToCacheTemplateWithId:error:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:failedtocachetemplatewithid:error:)","navigatorTitle":[{"text":"templatesManager:failedToCacheTemplateWithId:error:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:failedToCacheTemplateWithId:error:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:failedToCacheTemplateWithId:error:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"failedToCacheTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:cacheInProgressTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheinprogresstemplatewithid:)","navigatorTitle":[{"text":"templatesManager:cacheInProgressTemplateWithId:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:cacheInProgressTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheInProgressTemplateWithId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"kind":"text","text":", "},{"text":"cacheInProgressTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt/DSMHandler":{"navigatorTitle":[{"text":"DSMHandler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSMHandler"}],"url":"\/documentation\/volt\/dsmhandler","abstract":[],"kind":"symbol","title":"DSMHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMHandler","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:cachedTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cachedtemplatewithid:)","navigatorTitle":[{"text":"templatesManager:cachedTemplateWithId:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:cachedTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cachedTemplateWithId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier","text":"DSMTemplatesManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cachedTemplateWithId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/SH":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/SH","title":"Swift.Hashable"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:cacheUpdateInProgressTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheupdateinprogresstemplatewithid:)","navigatorTitle":[{"text":"templatesManager:cacheUpdateInProgressTemplateWithId:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:cacheUpdateInProgressTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheUpdateInProgressTemplateWithId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"kind":"text","text":", "},{"text":"cacheUpdateInProgressTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DSMTemplateHandler","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSMTemplateHandler"}]},{"value":[{"text":"DSMTemplateHandler","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/init","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheInProgressTemplateWithId:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheUpdateInProgressTemplateWithId:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cachedTemplateWithId:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:failedToCacheTemplateWithId:error:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:uncachedTemplateWithId:)"]}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)DSMTemplatesManagerDelegate"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSMTemplateHandler"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/title","value":"DSMTemplateHandler","op":"replace"},{"value":[{"kind":"identifier","text":"DSMTemplateHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/fragments"},{"op":"replace","value":"templatesManager:uncachedTemplateWithId:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:uncachedTemplateWithId:)\/title"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:uncachedTemplateWithId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"templatesManager:uncachedTemplateWithId:","kind":"identifier"}],"op":"replace"},{"value":"templatesManager:failedToCacheTemplateWithId:error:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:failedToCacheTemplateWithId:error:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"templatesManager:failedToCacheTemplateWithId:error:"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:failedToCacheTemplateWithId:error:)\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheInProgressTemplateWithId:)\/title","op":"replace","value":"templatesManager:cacheInProgressTemplateWithId:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"templatesManager:cacheInProgressTemplateWithId:"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheInProgressTemplateWithId:)\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cachedTemplateWithId:)\/title","op":"replace","value":"templatesManager:cachedTemplateWithId:"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cachedTemplateWithId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"templatesManager:cachedTemplateWithId:"}]},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheUpdateInProgressTemplateWithId:)\/title","value":"templatesManager:cacheUpdateInProgressTemplateWithId:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"templatesManager:cacheUpdateInProgressTemplateWithId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheUpdateInProgressTemplateWithId:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}