{"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","doc:\/\/com.KCDev.Volt\/objc(pl)FIRMessagingDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)NSObject","doc:\/\/com.KCDev.Volt\/s7CVarArgP","doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP","doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","doc:\/\/com.KCDev.Volt\/SQ","doc:\/\/com.KCDev.Volt\/SH","doc:\/\/com.KCDev.Volt\/objc(pl)UIApplicationDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)UNUserNotificationCenterDelegate"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@Volt@objc(cs)FirebaseAppDelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FirebaseAppDelegate","kind":"identifier"}],"modules":[{"name":"Volt"}],"symbolKind":"class","title":"FirebaseAppDelegate","role":"symbol"},"variants":[{"paths":["\/documentation\/volt\/firebaseappdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/init()"]},{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/authManager","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/gcmMessageIDKey","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/launchedBefore","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userDefaults"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:open:options:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/MessagingDelegate-Implementations","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UIApplicationDelegate-Implementations","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations"]}],"references":{"doc://com.KCDev.Volt/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"fetchCompletionHandler"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)","abstract":[],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","role":"symbol"},"doc://com.KCDev.Volt/objc(pl)UIApplicationDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)UIApplicationDelegate","title":"UIApplicationDelegate"},"doc://com.KCDev.Volt/SH":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/SH","title":"Swift.Hashable"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/launchedBefore":{"url":"\/documentation\/volt\/firebaseappdelegate\/launchedbefore","kind":"symbol","abstract":[],"title":"launchedBefore","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"launchedBefore"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/launchedBefore"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/UNUserNotificationCenterDelegate-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"UNUserNotificationCenterDelegate Implementations","type":"topic","url":"\/documentation\/volt\/firebaseappdelegate\/unusernotificationcenterdelegate-implementations"},"doc://com.KCDev.Volt/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(cs)NSObject","title":"NSObject"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/authManager":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/authManager","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authManager"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4Volt11AuthManagerC","text":"AuthManager"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/authmanager","title":"authManager"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/UIApplicationDelegate-Implementations":{"url":"\/documentation\/volt\/firebaseappdelegate\/uiapplicationdelegate-implementations","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UIApplicationDelegate-Implementations","role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"kind":"article"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/gcmMessageIDKey":{"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/volt\/firebaseappdelegate\/gcmmessageidkey","kind":"symbol","title":"gcmMessageIDKey","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/gcmMessageIDKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gcmMessageIDKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.KCDev.Volt/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/init()":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/init()","abstract":[],"url":"\/documentation\/volt\/firebaseappdelegate\/init()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.KCDev.Volt/objc(pl)DSM_Optional":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","title":"DocuSignSDK.DSM_Optional"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/userDefaults":{"title":"userDefaults","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userDefaults"},{"kind":"text","text":": "},{"text":"UserDefaults","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUserDefaults"}],"url":"\/documentation\/volt\/firebaseappdelegate\/userdefaults","abstract":[],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userDefaults"},"doc://com.KCDev.Volt/objc(pl)DSM_Ignore":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","title":"DocuSignSDK.DSM_Ignore"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/MessagingDelegate-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/volt\/firebaseappdelegate\/messagingdelegate-implementations","kind":"article","title":"MessagingDelegate Implementations","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/MessagingDelegate-Implementations"},"doc://com.KCDev.Volt/objc(pl)UNUserNotificationCenterDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)UNUserNotificationCenterDelegate","title":"UNUserNotificationCenterDelegate"},"doc://com.KCDev.Volt/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.KCDev.Volt/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/SQ","title":"Swift.Equatable"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:open:options:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"open"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey","text":"OpenURLOptionsKey","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"application:openURL:options:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/application(_:open:options:)","abstract":[],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:open:options:)","title":"application(_:open:options:)","role":"symbol"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)":{"kind":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)","navigatorTitle":[{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"role":"symbol","title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRegisterForRemoteNotificationsWithDeviceToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:didFinishLaunchingWithOptions:)":{"url":"\/documentation\/volt\/firebaseappdelegate\/application(_:didfinishlaunchingwithoptions:)","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"application(_:didFinishLaunchingWithOptions:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/objc(pl)FIRMessagingDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)FIRMessagingDelegate","title":"FIRMessagingDelegate"},"doc://com.KCDev.Volt/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.KCDev.Volt\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"FirebaseAppDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FirebaseAppDelegate"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:open:options:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/init()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/MessagingDelegate-Implementations","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations"],"title":"Default Implementations","generated":true}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)FIRMessagingDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)UIApplicationDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)UNUserNotificationCenterDelegate"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"FirebaseAppDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}],"op":"replace"},{"value":"init","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1init()\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:open:options:)\/title","value":"application:openURL:options:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:openURL:options:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:open:options:)\/fragments"},{"value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/title"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","op":"replace","value":"application:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},{"op":"replace","value":"FirebaseAppDelegate","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"text":"FirebaseAppDelegate","kind":"identifier"}]}]}]}