{"seeAlsoSections":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/UserManager","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AuthHandler","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInGoogleHelper","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/PhoneSignUpForm","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/EmailSignInForm","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/UserHandler","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/UserProfileViewModel"],"title":"User Management","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SignInAppleHelper","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/volt\/signinapplehelper"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/signinapplehelper"]}],"topicSections":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/startSignInWithAppleFlow()","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/startSignInWithAppleFlow(completion:)"],"title":"Instance Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations"]}],"metadata":{"externalID":"c:@M@Volt@objc(cs)SignInAppleHelper","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SignInAppleHelper"}],"modules":[{"name":"Volt"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SignInAppleHelper","kind":"identifier"}],"symbolKind":"class","title":"SignInAppleHelper","roleHeading":"Class"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerDelegate","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","doc:\/\/com.KCDev.Volt\/objc(pl)NSObject","doc:\/\/com.KCDev.Volt\/s7CVarArgP","doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP","doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","doc:\/\/com.KCDev.Volt\/SQ","doc:\/\/com.KCDev.Volt\/SH","doc:\/\/com.KCDev.Volt\/s8SendableP"],"kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","interfaceLanguage":"swift"},"references":{"doc://com.KCDev.Volt/documentation/Volt/EmailSignInForm":{"navigatorTitle":[{"text":"EmailSignInForm","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/EmailSignInForm","abstract":[],"url":"\/documentation\/volt\/emailsigninform","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmailSignInForm"}],"title":"EmailSignInForm","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/startSignInWithAppleFlow()":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/startSignInWithAppleFlow()","type":"topic","kind":"symbol","title":"startSignInWithAppleFlow()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startSignInWithAppleFlow","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:4Volt21SignInWithAppleResultV","text":"SignInWithAppleResult","kind":"typeIdentifier"}],"url":"\/documentation\/volt\/signinapplehelper\/startsigninwithappleflow()","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/ASAuthorizationControllerDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations","abstract":[],"title":"ASAuthorizationControllerDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/volt\/signinapplehelper\/asauthorizationcontrollerdelegate-implementations"},"doc://com.KCDev.Volt/documentation/Volt/UserManager":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/UserManager","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/usermanager","title":"UserManager","navigatorTitle":[{"kind":"identifier","text":"UserManager"}],"abstract":[{"code":"UserManager","type":"codeVoice"},{"type":"text","text":" manages the operations related to user accounts in the Volt app."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserManager"}]},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/startSignInWithAppleFlow(completion:)":{"abstract":[],"url":"\/documentation\/volt\/signinapplehelper\/startsigninwithappleflow(completion:)","title":"startSignInWithAppleFlow(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startSignInWithAppleFlow","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"SignInWithAppleResult","preciseIdentifier":"s:4Volt21SignInWithAppleResultV"},{"kind":"text","text":", "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/startSignInWithAppleFlow(completion:)"},"doc://com.KCDev.Volt/documentation/Volt/PhoneSignUpForm":{"role":"symbol","url":"\/documentation\/volt\/phonesignupform","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PhoneSignUpForm","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PhoneSignUpForm","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/PhoneSignUpForm","title":"PhoneSignUpForm","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[],"url":"\/documentation\/volt\/signinapplehelper\/init","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic","title":"init"},"doc://com.KCDev.Volt/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.KCDev.Volt\/objc(cs)NSObject","type":"unresolvable"},"doc://com.KCDev.Volt/objc(pl)DSM_Ignore":{"title":"DocuSignSDK.DSM_Ignore","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Ignore","type":"unresolvable"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.KCDev.Volt\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.KCDev.Volt/documentation/Volt/UserHandler":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/UserHandler","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/userhandler","title":"UserHandler","navigatorTitle":[{"kind":"identifier","text":"UserHandler"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserHandler"}]},"doc://com.KCDev.Volt/documentation/Volt/AuthHandler":{"url":"\/documentation\/volt\/authhandler","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthHandler"}],"abstract":[],"type":"topic","title":"AuthHandler","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AuthHandler","role":"symbol"},"doc://com.KCDev.Volt/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.KCDev.Volt\/s7CVarArgP","type":"unresolvable"},"doc://com.KCDev.Volt/objc(pl)DSM_Optional":{"title":"DocuSignSDK.DSM_Optional","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)DSM_Optional","type":"unresolvable"},"doc://com.KCDev.Volt/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.KCDev.Volt\/SH"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/signinapplehelper","title":"SignInAppleHelper","navigatorTitle":[{"text":"SignInAppleHelper","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInAppleHelper","kind":"identifier"}]},"doc://com.KCDev.Volt/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.KCDev.Volt\/s28CustomDebugStringConvertibleP"},"doc://com.KCDev.Volt/documentation/Volt/UserProfileViewModel":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/UserProfileViewModel","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/userprofileviewmodel","title":"UserProfileViewModel","navigatorTitle":[{"kind":"identifier","text":"UserProfileViewModel"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserProfileViewModel"}]},"doc://com.KCDev.Volt/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.KCDev.Volt\/SQ"},"doc://com.KCDev.Volt/documentation/Volt/SignInGoogleHelper":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInGoogleHelper","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/signingooglehelper","title":"SignInGoogleHelper","navigatorTitle":[{"kind":"identifier","text":"SignInGoogleHelper"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SignInGoogleHelper"}]},"doc://com.KCDev.Volt/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.KCDev.Volt\/s8SendableP"},"doc://com.KCDev.Volt/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)NSObject"},"doc://com.KCDev.Volt/objc(pl)ASAuthorizationControllerDelegate":{"type":"unresolvable","title":"ASAuthorizationControllerDelegate","identifier":"doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SignInAppleHelper","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SignInAppleHelper","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SignInAppleHelper"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/init"],"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.KCDev.Volt\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.KCDev.Volt\/objc(pl)ASAuthorizationControllerDelegate"]}]},{"value":null,"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInAppleHelper","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/title","op":"replace","value":"SignInAppleHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/fragments","value":[{"text":"SignInAppleHelper","kind":"identifier"}]}]}]}