{"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cachedTemplateWithId:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cachedtemplatewithid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cachedtemplatewithid:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DSMTemplatesManagerDelegate.templatesManager(_:cachedTemplateWithId:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"modules":[{"name":"Volt"}],"navigatorTitle":[{"kind":"identifier","text":"templatesManager:cachedTemplateWithId:"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"text":", ","kind":"text"},{"text":"cachedTemplateWithId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@Volt@objc(cs)DSMTemplateHandler(im)templatesManager:cachedTemplateWithId:","title":"templatesManager(_:cachedTemplateWithId:)"},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templatesManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cachedTemplateWithId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:cachedTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cachedtemplatewithid:)","navigatorTitle":[{"text":"templatesManager:cachedTemplateWithId:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:cachedTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cachedTemplateWithId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier","text":"DSMTemplatesManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cachedTemplateWithId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSMTemplateHandler","kind":"identifier"}],"url":"\/documentation\/volt\/dsmtemplatehandler","abstract":[],"kind":"symbol","title":"DSMTemplateHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"templatesManager:cachedTemplateWithId:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"templatesManager:cachedTemplateWithId:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"templatesManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","text":"DSMTemplatesManager"},{"text":" *) ","kind":"text"},{"text":"templatesManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cachedTemplateWithId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"templateId"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cachedTemplateWithId:)\/title","value":"templatesManager:cachedTemplateWithId:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"templatesManager:cachedTemplateWithId:"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cachedTemplateWithId:)\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/title","value":"DSMTemplateHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/fragments","value":[{"kind":"identifier","text":"DSMTemplateHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}