{"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DSMTemplatesManagerDelegate.templatesManager(_:uncachedTemplateWithId:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"templatesManager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier","text":"DSMTemplatesManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"uncachedTemplateWithId"},{"text":" ","kind":"text"},{"text":"templateId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@Volt@objc(cs)DSMTemplateHandler(im)templatesManager:uncachedTemplateWithId:","navigatorTitle":[{"kind":"identifier","text":"templatesManager:uncachedTemplateWithId:"}],"symbolKind":"method","modules":[{"name":"Volt"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"uncachedTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","title":"templatesManager(_:uncachedTemplateWithId:)"},"sections":[],"variants":[{"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:uncachedtemplatewithid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:uncachedtemplatewithid:)"]}],"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:uncachedTemplateWithId:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:uncachedTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:uncachedtemplatewithid:)","navigatorTitle":[{"kind":"identifier","text":"templatesManager:uncachedTemplateWithId:"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:uncachedTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:uncachedTemplateWithId:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSMTemplatesManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"text":", ","kind":"text"},{"text":"uncachedTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSMTemplateHandler","kind":"identifier"}],"url":"\/documentation\/volt\/dsmtemplatehandler","abstract":[],"kind":"symbol","title":"DSMTemplateHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"templatesManager:uncachedTemplateWithId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"templatesManager:uncachedTemplateWithId:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"templatesManager:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSMTemplatesManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"kind":"text","text":" *) "},{"text":"templatesManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"uncachedTemplateWithId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"templateId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"templatesManager:uncachedTemplateWithId:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:uncachedTemplateWithId:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"templatesManager:uncachedTemplateWithId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:uncachedTemplateWithId:)\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/title","value":"DSMTemplateHandler","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/fragments","value":[{"text":"DSMTemplateHandler","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}