{"variants":[{"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:failedtocachetemplatewithid:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:failedtocachetemplatewithid:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"templatesManager","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DSMTemplatesManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"text":", ","kind":"text"},{"text":"failedToCacheTemplateWithId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"templateId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:failedToCacheTemplateWithId:error:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DSMTemplatesManagerDelegate.templatesManager(_:failedToCacheTemplateWithId:error:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler"]]},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"templatesManager:failedToCacheTemplateWithId:error:"}],"title":"templatesManager(_:failedToCacheTemplateWithId:error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSMTemplatesManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failedToCacheTemplateWithId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"modules":[{"name":"Volt"}],"externalID":"c:@M@Volt@objc(cs)DSMTemplateHandler(im)templatesManager:failedToCacheTemplateWithId:error:","roleHeading":"Instance Method"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:failedToCacheTemplateWithId:error:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:failedtocachetemplatewithid:error:)","navigatorTitle":[{"text":"templatesManager:failedToCacheTemplateWithId:error:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:failedToCacheTemplateWithId:error:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:failedToCacheTemplateWithId:error:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"failedToCacheTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSMTemplateHandler","kind":"identifier"}],"url":"\/documentation\/volt\/dsmtemplatehandler","abstract":[],"kind":"symbol","title":"DSMTemplateHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"templatesManager:failedToCacheTemplateWithId:error:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"templatesManager:failedToCacheTemplateWithId:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"templatesManager:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"templatesManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedToCacheTemplateWithId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"templateId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:failedToCacheTemplateWithId:error:)\/title","value":"templatesManager:failedToCacheTemplateWithId:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:failedToCacheTemplateWithId:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"templatesManager:failedToCacheTemplateWithId:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/title","op":"replace","value":"DSMTemplateHandler"},{"op":"replace","value":[{"text":"DSMTemplateHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}