{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"templatesManager:cacheInProgressTemplateWithId:"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"templatesManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DSMTemplatesManager","text":"DSMTemplatesManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cacheInProgressTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"Volt"}],"title":"templatesManager(_:cacheInProgressTemplateWithId:)","externalID":"c:@M@Volt@objc(cs)DSMTemplateHandler(im)templatesManager:cacheInProgressTemplateWithId:"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DSMTemplatesManagerDelegate.templatesManager(_:cacheInProgressTemplateWithId:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templatesManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"templatesManager"},{"text":": ","kind":"text"},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cacheInProgressTemplateWithId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheInProgressTemplateWithId:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheinprogresstemplatewithid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheinprogresstemplatewithid:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSMTemplateHandler","kind":"identifier"}],"url":"\/documentation\/volt\/dsmtemplatehandler","abstract":[],"kind":"symbol","title":"DSMTemplateHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:cacheInProgressTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheinprogresstemplatewithid:)","navigatorTitle":[{"text":"templatesManager:cacheInProgressTemplateWithId:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:cacheInProgressTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheInProgressTemplateWithId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"kind":"text","text":", "},{"text":"cacheInProgressTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"templatesManager:cacheInProgressTemplateWithId:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"templatesManager:cacheInProgressTemplateWithId:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"templatesManager:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"templatesManager"},{"kind":"text","text":" "},{"text":"cacheInProgressTemplateWithId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"templateId","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/title","op":"replace","value":"DSMTemplateHandler"},{"value":[{"kind":"identifier","text":"DSMTemplateHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheInProgressTemplateWithId:)\/title","value":"templatesManager:cacheInProgressTemplateWithId:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"templatesManager:cacheInProgressTemplateWithId:"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheInProgressTemplateWithId:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}