{"metadata":{"modules":[{"name":"Volt"}],"navigatorTitle":[{"kind":"identifier","text":"templatesManager:cacheUpdateInProgressTemplateWithId:"}],"externalID":"c:@M@Volt@objc(cs)DSMTemplateHandler(im)templatesManager:cacheUpdateInProgressTemplateWithId:","roleHeading":"Instance Method","title":"templatesManager(_:cacheUpdateInProgressTemplateWithId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","text":"DSMTemplatesManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cacheUpdateInProgressTemplateWithId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol"},"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheUpdateInProgressTemplateWithId:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheupdateinprogresstemplatewithid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheupdateinprogresstemplatewithid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DSMTemplatesManagerDelegate.templatesManager(_:cacheUpdateInProgressTemplateWithId:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"templatesManager","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DSMTemplatesManager","text":"DSMTemplatesManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheUpdateInProgressTemplateWithId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"templateId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler"]]},"references":{"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler":{"navigatorTitle":[{"kind":"identifier","text":"DSMTemplateHandler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSMTemplateHandler","kind":"identifier"}],"url":"\/documentation\/volt\/dsmtemplatehandler","abstract":[],"kind":"symbol","title":"DSMTemplateHandler","role":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler","type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/DSMTemplateHandler/templatesManager(_:cacheUpdateInProgressTemplateWithId:)":{"role":"symbol","url":"\/documentation\/volt\/dsmtemplatehandler\/templatesmanager(_:cacheupdateinprogresstemplatewithid:)","navigatorTitle":[{"text":"templatesManager:cacheUpdateInProgressTemplateWithId:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"templatesManager(_:cacheUpdateInProgressTemplateWithId:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/DSMTemplateHandler\/templatesManager(_:cacheUpdateInProgressTemplateWithId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatesManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DSMTemplatesManager","preciseIdentifier":"c:objc(cs)DSMTemplatesManager"},{"kind":"text","text":", "},{"text":"cacheUpdateInProgressTemplateWithId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"templatesManager:cacheUpdateInProgressTemplateWithId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"templatesManager:cacheUpdateInProgressTemplateWithId:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"templatesManager:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DSMTemplatesManager","kind":"typeIdentifier","text":"DSMTemplatesManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"templatesManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cacheUpdateInProgressTemplateWithId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"templateId"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/title","value":"DSMTemplateHandler"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler\/fragments","value":[{"text":"DSMTemplateHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheUpdateInProgressTemplateWithId:)\/title","value":"templatesManager:cacheUpdateInProgressTemplateWithId:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"templatesManager:cacheUpdateInProgressTemplateWithId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1DSMTemplateHandler~1templatesManager(_:cacheUpdateInProgressTemplateWithId:)\/fragments","op":"replace"}]}]}