{"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithAuthorization:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithError:)"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/signinapplehelper\/asauthorizationcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/signinapplehelper\/asauthorizationcontrollerdelegate-implementations"]}],"metadata":{"modules":[{"name":"Volt"}],"role":"collectionGroup","title":"ASAuthorizationControllerDelegate Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper"]]},"sections":[],"references":{"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/signinapplehelper","title":"SignInAppleHelper","navigatorTitle":[{"text":"SignInAppleHelper","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInAppleHelper","kind":"identifier"}]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/authorizationController(controller:didCompleteWithError:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didCompleteWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"title":"authorizationController(controller:didCompleteWithError:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithError:)","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"role":"symbol","url":"\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewitherror:)"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/authorizationController(controller:didCompleteWithAuthorization:)":{"title":"authorizationController(controller:didCompleteWithAuthorization:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithAuthorization:)","url":"\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewithauthorization:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController"},{"kind":"text","text":", "},{"text":"didCompleteWithAuthorization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithAuthorization:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithError:)"],"generated":true,"title":"Instance Methods"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"SignInAppleHelper","op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/title"},{"value":[{"kind":"identifier","text":"SignInAppleHelper"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithError:)\/title","value":"authorizationController:didCompleteWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithAuthorization:)\/title","value":"authorizationController:didCompleteWithAuthorization:"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithAuthorization:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"authorizationController:didCompleteWithAuthorization:","kind":"identifier"}],"op":"replace"}]}]}