{"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewithauthorization:)"]},{"paths":["\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewithauthorization:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authorizationController"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithAuthorization"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authorization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","extendedModule":"Volt","symbolKind":"method","title":"authorizationController(controller:didCompleteWithAuthorization:)","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"modules":[{"name":"Volt"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"text":", ","kind":"text"},{"text":"didCompleteWithAuthorization","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization"},{"kind":"text","text":")"}],"externalID":"c:@CM@Volt@objc(cs)SignInAppleHelper(im)authorizationController:didCompleteWithAuthorization:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithAuthorization:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASAuthorizationControllerDelegate.authorizationController(controller:didCompleteWithAuthorization:)"},{"type":"text","text":"."}],"references":{"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/ASAuthorizationControllerDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations","abstract":[],"title":"ASAuthorizationControllerDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/volt\/signinapplehelper\/asauthorizationcontrollerdelegate-implementations"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/signinapplehelper","title":"SignInAppleHelper","navigatorTitle":[{"text":"SignInAppleHelper","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInAppleHelper","kind":"identifier"}]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/authorizationController(controller:didCompleteWithAuthorization:)":{"title":"authorizationController(controller:didCompleteWithAuthorization:)","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithAuthorization:)","url":"\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewithauthorization:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController"},{"kind":"text","text":", "},{"text":"didCompleteWithAuthorization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"authorizationController:didCompleteWithAuthorization:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"authorizationController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCompleteWithAuthorization:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"authorization"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/title","value":"SignInAppleHelper"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/fragments","value":[{"kind":"identifier","text":"SignInAppleHelper"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithAuthorization:)\/title","value":"authorizationController:didCompleteWithAuthorization:"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithAuthorization:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"op":"replace"}]}]}