{"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithError:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"ASAuthorizationControllerDelegate.authorizationController(controller:didCompleteWithError:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"authorizationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","kind":"typeIdentifier","text":"ASAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWithError"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewitherror:)"]}],"metadata":{"externalID":"c:@CM@Volt@objc(cs)SignInAppleHelper(im)authorizationController:didCompleteWithError:","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"role":"symbol","title":"authorizationController(controller:didCompleteWithError:)","symbolKind":"method","modules":[{"name":"Volt"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/authorizationController(controller:didCompleteWithError:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didCompleteWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"title":"authorizationController(controller:didCompleteWithError:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/authorizationController(controller:didCompleteWithError:)","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"role":"symbol","url":"\/documentation\/volt\/signinapplehelper\/authorizationcontroller(controller:didcompletewitherror:)"},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/volt\/signinapplehelper","title":"SignInAppleHelper","navigatorTitle":[{"text":"SignInAppleHelper","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInAppleHelper","kind":"identifier"}]},"doc://com.KCDev.Volt/documentation/Volt/SignInAppleHelper/ASAuthorizationControllerDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/SignInAppleHelper\/ASAuthorizationControllerDelegate-Implementations","abstract":[],"title":"ASAuthorizationControllerDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/volt\/signinapplehelper\/asauthorizationcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"authorizationController:didCompleteWithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"authorizationController:didCompleteWithError:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"authorizationController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"text":"didCompleteWithError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithError:)\/title","op":"replace","value":"authorizationController:didCompleteWithError:"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper~1authorizationController(controller:didCompleteWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"authorizationController:didCompleteWithError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/title","value":"SignInAppleHelper"},{"value":[{"kind":"identifier","text":"SignInAppleHelper"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1SignInAppleHelper\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}