{"kind":"symbol","identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"text":", ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"fetchCompletionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"Volt"}],"navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"symbolKind":"method","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","externalID":"c:@M@Volt@objc(cs)FirebaseAppDelegate(im)application:didReceiveRemoteNotification:fetchCompletionHandler:","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIApplicationDelegate.application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"fetchCompletionHandler"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)","abstract":[],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","role":"symbol"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"application:didReceiveRemoteNotification:fetchCompletionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"text":"didReceiveRemoteNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":" "},{"text":"fetchCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#$@E@UIBackgroundFetchResult)","kind":"typeIdentifier","text":"void (^)(enum UIBackgroundFetchResult)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"application:didReceiveRemoteNotification:fetchCompletionHandler:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","value":"FirebaseAppDelegate"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"kind":"identifier","text":"FirebaseAppDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}