{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)"]}],"metadata":{"role":"symbol","title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","modules":[{"name":"Volt"}],"navigatorTitle":[{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@Volt@objc(cs)FirebaseAppDelegate(im)application:didRegisterForRemoteNotificationsWithDeviceToken:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didRegisterForRemoteNotificationsWithDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRegisterForRemoteNotificationsWithDeviceToken"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"deviceToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIApplicationDelegate.application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)":{"kind":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)","navigatorTitle":[{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"role":"symbol","title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRegisterForRemoteNotificationsWithDeviceToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":" *) ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceToken"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/title","op":"replace","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/fragments"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","op":"replace","value":"FirebaseAppDelegate"},{"value":[{"kind":"identifier","text":"FirebaseAppDelegate"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","op":"replace"}]}]}