{"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didFinishLaunchingWithOptions:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"text":" ","kind":"text"},{"text":"launchOptions","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]? = nil) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/application(_:didfinishlaunchingwithoptions:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/application(_:didfinishlaunchingwithoptions:)"]}],"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","title":"application(_:didFinishLaunchingWithOptions:)","roleHeading":"Instance Method","modules":[{"name":"Volt"}],"externalID":"c:@M@Volt@objc(cs)FirebaseAppDelegate(im)application:didFinishLaunchingWithOptions:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"text":"didFinishLaunchingWithOptions","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier","text":"LaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIApplicationDelegate.application(_:didFinishLaunchingWithOptions:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/application(_:didFinishLaunchingWithOptions:)":{"url":"\/documentation\/volt\/firebaseappdelegate\/application(_:didfinishlaunchingwithoptions:)","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/application(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"application(_:didFinishLaunchingWithOptions:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"application:didFinishLaunchingWithOptions:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"application"},{"text":" ","kind":"text"},{"text":"didFinishLaunchingWithOptions:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"launchOptions"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","value":"FirebaseAppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"text":"FirebaseAppDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:"},{"value":[{"kind":"text","text":"- "},{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","op":"replace"}]}]}