{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/messaging(_:didReceiveRegistrationToken:)"},"metadata":{"externalID":"c:@CM@Volt@objc(cs)FirebaseAppDelegate(im)messaging:didReceiveRegistrationToken:","roleHeading":"Instance Method","modules":[{"name":"Volt"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messaging","kind":"identifier"},{"kind":"text","text":"("},{"text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"extendedModule":"Volt","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}],"title":"messaging(_:didReceiveRegistrationToken:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessagingDelegate.messaging(_:didReceiveRegistrationToken:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messaging"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"messaging","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fcmToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/volt\/firebaseappdelegate\/messaging(_:didreceiveregistrationtoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/firebaseappdelegate\/messaging(_:didreceiveregistrationtoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/MessagingDelegate-Implementations"]]},"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/messaging(_:didReceiveRegistrationToken:)":{"role":"symbol","navigatorTitle":[{"text":"messaging:didReceiveRegistrationToken:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/volt\/firebaseappdelegate\/messaging(_:didreceiveregistrationtoken:)","kind":"symbol","title":"messaging(_:didReceiveRegistrationToken:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"text":", ","kind":"text"},{"text":"didReceiveRegistrationToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/messaging(_:didReceiveRegistrationToken:)"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/MessagingDelegate-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/volt\/firebaseappdelegate\/messagingdelegate-implementations","kind":"article","title":"MessagingDelegate Implementations","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/MessagingDelegate-Implementations"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messaging:didReceiveRegistrationToken:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"messaging:didReceiveRegistrationToken:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"messaging:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)FIRMessaging","text":"FIRMessaging","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"messaging","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveRegistrationToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fcmToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"messaging:didReceiveRegistrationToken:","op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1messaging(_:didReceiveRegistrationToken:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"messaging:didReceiveRegistrationToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1messaging(_:didReceiveRegistrationToken:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","value":"FirebaseAppDelegate","op":"replace"},{"value":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","op":"replace"}]}]}