{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/MessagingDelegate-Implementations"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/messaging(_:didReceiveRegistrationToken:)"],"generated":true}],"metadata":{"title":"MessagingDelegate Implementations","role":"collectionGroup","modules":[{"name":"Volt"}]},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/messagingdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/messagingdelegate-implementations"]}],"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/messaging(_:didReceiveRegistrationToken:)":{"role":"symbol","navigatorTitle":[{"text":"messaging:didReceiveRegistrationToken:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/volt\/firebaseappdelegate\/messaging(_:didreceiveregistrationtoken:)","kind":"symbol","title":"messaging(_:didReceiveRegistrationToken:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"text":", ","kind":"text"},{"text":"didReceiveRegistrationToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/messaging(_:didReceiveRegistrationToken:)"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/messaging(_:didReceiveRegistrationToken:)"],"title":"Instance Methods","generated":true}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","value":"FirebaseAppDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"kind":"identifier","text":"FirebaseAppDelegate"}],"op":"replace"},{"value":"messaging:didReceiveRegistrationToken:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1messaging(_:didReceiveRegistrationToken:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1messaging(_:didReceiveRegistrationToken:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"messaging:didReceiveRegistrationToken:","kind":"identifier"}],"op":"replace"}]}]}