{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"],"generated":true}],"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"role":"collectionGroup","modules":[{"name":"Volt"}],"title":"UNUserNotificationCenterDelegate Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/volt\/firebaseappdelegate\/unusernotificationcenterdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/unusernotificationcenterdelegate-implementations"]}],"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresent"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)","abstract":[],"role":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)","kind":"symbol","navigatorTitle":[{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}],"title":"userNotificationCenter(_:willPresent:withCompletionHandler:)"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","type":"topic","url":"\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)","navigatorTitle":[{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"FirebaseAppDelegate","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"kind":"identifier","text":"FirebaseAppDelegate"}]},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/title","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","op":"replace","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments"}]}]}