{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"Volt"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willPresent"},{"kind":"text","text":": "},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}],"extendedModule":"Volt","title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","symbolKind":"method","role":"symbol","externalID":"c:@CM@Volt@objc(cs)FirebaseAppDelegate(im)userNotificationCenter:willPresentNotification:withCompletionHandler:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"center"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"text":"willPresent","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UNUserNotificationCenterDelegate.userNotificationCenter(_:willPresent:withCompletionHandler:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)"]}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations"]]},"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/UNUserNotificationCenterDelegate-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"UNUserNotificationCenterDelegate Implementations","type":"topic","url":"\/documentation\/volt\/firebaseappdelegate\/unusernotificationcenterdelegate-implementations"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresent"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)","abstract":[],"role":"symbol","url":"\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)","kind":"symbol","navigatorTitle":[{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}],"title":"userNotificationCenter(_:willPresent:withCompletionHandler:)"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"userNotificationCenter:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"center","kind":"internalParam"},{"kind":"text","text":" "},{"text":"willPresentNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"notification"},{"text":" ","kind":"text"},{"text":"withCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(enum UNNotificationPresentationOptions)","preciseIdentifier":"c:BFv(#$@E@UNNotificationPresentationOptions)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/title","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments"},{"value":"FirebaseAppDelegate","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"text":"FirebaseAppDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}