{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"center"},{"kind":"text","text":": "},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UNUserNotificationCenterDelegate.userNotificationCenter(_:didReceive:withCompletionHandler:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:@CM@Volt@objc(cs)FirebaseAppDelegate(im)userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","modules":[{"name":"Volt"}],"roleHeading":"Instance Method","extendedModule":"Volt","symbolKind":"method","title":"userNotificationCenter(_:didReceive:withCompletionHandler:)"},"variants":[{"paths":["\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)"},"sections":[],"references":{"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate":{"url":"\/documentation\/volt\/firebaseappdelegate","navigatorTitle":[{"text":"FirebaseAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FirebaseAppDelegate"}],"title":"FirebaseAppDelegate","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","type":"topic","url":"\/documentation\/volt\/firebaseappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)","navigatorTitle":[{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}]},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/FirebaseAppDelegate/UNUserNotificationCenterDelegate-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/FirebaseAppDelegate\/UNUserNotificationCenterDelegate-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"UNUserNotificationCenterDelegate Implementations","type":"topic","url":"\/documentation\/volt\/firebaseappdelegate\/unusernotificationcenterdelegate-implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"userNotificationCenter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"kind":"text","text":" *) "},{"text":"center","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didReceiveNotificationResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withCompletionHandler:"},{"text":"(","kind":"text"},{"text":"void (^)(void)","preciseIdentifier":"c:BFv()","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/title","value":"FirebaseAppDelegate"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate\/fragments","value":[{"kind":"identifier","text":"FirebaseAppDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1FirebaseAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}