{"metadata":{"modules":[{"name":"Volt"}],"title":"ASAuthorizationControllerDelegate Implementations","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/applesignin\/asauthorizationcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/applesignin\/asauthorizationcontrollerdelegate-implementations"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithAuthorization:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithError:)"],"title":"Instance Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn"]]},"references":{"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/authorizationController(controller:didCompleteWithError:)":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithError:)","abstract":[],"role":"symbol","url":"\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewitherror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWithError"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"title":"authorizationController(controller:didCompleteWithError:)"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/authorizationController(controller:didCompleteWithAuthorization:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"text":"didCompleteWithAuthorization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewithauthorization:)","title":"authorizationController(controller:didCompleteWithAuthorization:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"authorizationController:didCompleteWithAuthorization:","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithAuthorization:)"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn":{"url":"\/documentation\/volt\/applesignin","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleSignIn","kind":"identifier"}],"abstract":[],"title":"AppleSignIn","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithAuthorization:)","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithError:)"],"title":"Instance Methods"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithError:)\/title","value":"authorizationController:didCompleteWithError:"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}]},{"op":"replace","value":"authorizationController:didCompleteWithAuthorization:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithAuthorization:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"authorizationController:didCompleteWithAuthorization:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithAuthorization:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/title","value":"AppleSignIn"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/fragments","value":[{"text":"AppleSignIn","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}