{"variants":[{"paths":["\/documentation\/volt\/applesignin\/asauthorizationcontrollerpresentationcontextproviding-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/applesignin\/asauthorizationcontrollerpresentationcontextproviding-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/presentationAnchor(for:)"]}],"metadata":{"title":"ASAuthorizationControllerPresentationContextProviding Implementations","modules":[{"name":"Volt"}],"role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerPresentationContextProviding-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn"]]},"references":{"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn":{"url":"\/documentation\/volt\/applesignin","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleSignIn","kind":"identifier"}],"abstract":[],"title":"AppleSignIn","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","kind":"symbol"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/presentationAnchor(for:)":{"navigatorTitle":[{"text":"presentationAnchorForAuthorizationController:","kind":"identifier"}],"title":"presentationAnchor(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@ASPresentationAnchor","text":"ASPresentationAnchor","kind":"typeIdentifier"}],"url":"\/documentation\/volt\/applesignin\/presentationanchor(for:)","abstract":[],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/presentationAnchor(for:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/presentationAnchor(for:)"],"generated":true}],"path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/title","value":"AppleSignIn"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/fragments","value":[{"text":"AppleSignIn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1presentationAnchor(for:)\/title","value":"presentationAnchorForAuthorizationController:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationAnchorForAuthorizationController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1presentationAnchor(for:)\/fragments"}]}]}