{"sections":[],"variants":[{"paths":["\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewitherror:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWithError"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASAuthorizationControllerDelegate.authorizationController(controller:didCompleteWithError:)"},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithError:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"Volt"}],"navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"role":"symbol","title":"authorizationController(controller:didCompleteWithError:)","roleHeading":"Instance Method","externalID":"c:@CM@Volt@objc(cs)AppleSignIn(im)authorizationController:didCompleteWithError:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"extendedModule":"Volt"},"references":{"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn":{"url":"\/documentation\/volt\/applesignin","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleSignIn","kind":"identifier"}],"abstract":[],"title":"AppleSignIn","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","kind":"symbol"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/ASAuthorizationControllerDelegate-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations","type":"topic","url":"\/documentation\/volt\/applesignin\/asauthorizationcontrollerdelegate-implementations","title":"ASAuthorizationControllerDelegate Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/authorizationController(controller:didCompleteWithError:)":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithError:)","abstract":[],"role":"symbol","url":"\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewitherror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWithError"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"title":"authorizationController(controller:didCompleteWithError:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"authorizationController:didCompleteWithError:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"authorizationController:didCompleteWithError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"authorizationController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"didCompleteWithError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/title","value":"AppleSignIn","op":"replace"},{"value":[{"text":"AppleSignIn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/fragments"},{"value":"authorizationController:didCompleteWithError:","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"authorizationController:didCompleteWithError:","kind":"identifier"}]}]}]}