{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWithAuthorization"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authorization"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"externalID":"c:@CM@Volt@objc(cs)AppleSignIn(im)authorizationController:didCompleteWithAuthorization:","navigatorTitle":[{"text":"authorizationController:didCompleteWithAuthorization:","kind":"identifier"}],"title":"authorizationController(controller:didCompleteWithAuthorization:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteWithAuthorization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Volt","modules":[{"name":"Volt"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"ASAuthorizationControllerDelegate.authorizationController(controller:didCompleteWithAuthorization:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithAuthorization:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewithauthorization:)"]},{"paths":["\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewithauthorization:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/ASAuthorizationControllerDelegate-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerDelegate-Implementations","type":"topic","url":"\/documentation\/volt\/applesignin\/asauthorizationcontrollerdelegate-implementations","title":"ASAuthorizationControllerDelegate Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/authorizationController(controller:didCompleteWithAuthorization:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"text":"didCompleteWithAuthorization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorization","text":"ASAuthorization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/volt\/applesignin\/authorizationcontroller(controller:didcompletewithauthorization:)","title":"authorizationController(controller:didCompleteWithAuthorization:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"authorizationController:didCompleteWithAuthorization:","kind":"identifier"}],"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/authorizationController(controller:didCompleteWithAuthorization:)"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn":{"url":"\/documentation\/volt\/applesignin","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleSignIn","kind":"identifier"}],"abstract":[],"title":"AppleSignIn","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authorizationController:didCompleteWithAuthorization:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"authorizationController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","text":"ASAuthorizationController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteWithAuthorization:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ASAuthorization","kind":"typeIdentifier","text":"ASAuthorization"},{"text":" *) ","kind":"text"},{"text":"authorization","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithAuthorization:)\/title","op":"replace","value":"authorizationController:didCompleteWithAuthorization:"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1authorizationController(controller:didCompleteWithAuthorization:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}]},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/title","value":"AppleSignIn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/fragments","value":[{"kind":"identifier","text":"AppleSignIn"}]}]}]}