{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"Volt"}],"extendedModule":"Volt","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASAuthorizationController","kind":"typeIdentifier","text":"ASAuthorizationController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@ASPresentationAnchor","text":"ASPresentationAnchor"}],"title":"presentationAnchor(for:)","navigatorTitle":[{"text":"presentationAnchorForAuthorizationController:","kind":"identifier"}],"externalID":"c:@CM@Volt@objc(cs)AppleSignIn(im)presentationAnchorForAuthorizationController:","symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASAuthorizationControllerPresentationContextProviding.presentationAnchor(for:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@ASPresentationAnchor","text":"ASPresentationAnchor"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/volt\/applesignin\/presentationanchor(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/volt\/applesignin\/presentationanchor(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/presentationAnchor(for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.KCDev.Volt\/documentation\/Volt","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerPresentationContextProviding-Implementations"]]},"references":{"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn":{"url":"\/documentation\/volt\/applesignin","role":"symbol","navigatorTitle":[{"text":"AppleSignIn","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleSignIn","kind":"identifier"}],"abstract":[],"title":"AppleSignIn","type":"topic","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn","kind":"symbol"},"doc://com.KCDev.Volt/documentation/Volt":{"title":"Volt","url":"\/documentation\/volt","type":"topic","abstract":[{"text":"Volt is a comprehensive platform designed to manage various aspects of apprenticeship and training programs. It integrates several functionalities, from user management to course handling, making it an all-encompassing solution for educational and professional development needs.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt","role":"collection"},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/ASAuthorizationControllerPresentationContextProviding-Implementations":{"identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/ASAuthorizationControllerPresentationContextProviding-Implementations","type":"topic","url":"\/documentation\/volt\/applesignin\/asauthorizationcontrollerpresentationcontextproviding-implementations","title":"ASAuthorizationControllerPresentationContextProviding Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.KCDev.Volt/documentation/Volt/AppleSignIn/presentationAnchor(for:)":{"navigatorTitle":[{"text":"presentationAnchorForAuthorizationController:","kind":"identifier"}],"title":"presentationAnchor(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@ASPresentationAnchor","text":"ASPresentationAnchor","kind":"typeIdentifier"}],"url":"\/documentation\/volt\/applesignin\/presentationanchor(for:)","abstract":[],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.KCDev.Volt\/documentation\/Volt\/AppleSignIn\/presentationAnchor(for:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"presentationAnchorForAuthorizationController:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"presentationAnchorForAuthorizationController:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"},{"text":"(","kind":"text"},{"text":"ASAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/title","value":"AppleSignIn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn\/fragments","value":[{"kind":"identifier","text":"AppleSignIn"}]},{"path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1presentationAnchor(for:)\/title","value":"presentationAnchorForAuthorizationController:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.KCDev.Volt~1documentation~1Volt~1AppleSignIn~1presentationAnchor(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentationAnchorForAuthorizationController:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}